export const ADD_TO_CART = "ADD_TO_CART";
export const BUY_NOW = "BUY_NOW";
export const DELETE_ITEM_FROM_BASKET = "DELETE_ITEM_FROM_BASKET";
export const GET_PRODUCT_INFO = "GET_PRODUCT_INFO";
export const GET_CART_QUANTITY = "GET_CART_QUANTITY";
